version: "3.7"

services:
 bd:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: "root"
  ports:
   - "15432:5432"
  volumes:
   - /localdatasave
  networks:
   - postgres-compose-network

 pgadmin:
  image: dpage/pgadmin4
  environment:
   PGADMIN_DEFAULT_EMAIL: "youremail@email.com"
   PGADMIN_DEFAULT_PASSWORD: "root"
  ports:
   - "16543:80"
  depends_on:
   - bd
  networks:
   - postgres-compose-network

networks:
 postgres-compose-network:
  driver: bridge



